const courses = [
    {
        "Course_Title": "Marketing20",
        "Course_Duration": 128.5,
        "Level": "Advanced",
        "Enrollment_Count": 5,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/370/4928/3264.jpg?hmac=UGe0txSnG4hhV-fAoi7e3mTnvQFhYYNcPJJbYFePh5Q",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing19",
        "Course_Duration": 128.5,
        "Level": "Advanced",
        "Enrollment_Count": 5,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/370/4928/3264.jpg?hmac=UGe0txSnG4hhV-fAoi7e3mTnvQFhYYNcPJJbYFePh5Q",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing18",
        "Course_Duration": 128.5,
        "Level": "Advanced",
        "Enrollment_Count": 5,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/370/4928/3264.jpg?hmac=UGe0txSnG4hhV-fAoi7e3mTnvQFhYYNcPJJbYFePh5Q",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing17",
        "Course_Duration": 128.5,
        "Level": "Advanced",
        "Enrollment_Count": 5,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/370/4928/3264.jpg?hmac=UGe0txSnG4hhV-fAoi7e3mTnvQFhYYNcPJJbYFePh5Q",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing16",
        "Course_Duration": 128.5,
        "Level": "Advanced",
        "Enrollment_Count": 5,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/370/4928/3264.jpg?hmac=UGe0txSnG4hhV-fAoi7e3mTnvQFhYYNcPJJbYFePh5Q",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing15",
        "Course_Duration": 128.5,
        "Level": "Advanced",
        "Enrollment_Count": 5,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/370/4928/3264.jpg?hmac=UGe0txSnG4hhV-fAoi7e3mTnvQFhYYNcPJJbYFePh5Q",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing14",
        "Course_Duration": 5.3,
        "Level": "Advanced",
        "Enrollment_Count": 1205,
        "Status": "Open",
        "image": "/16_6.png",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing13",
        "Course_Duration": 5.3,
        "Level": "Advanced",
        "Enrollment_Count": 1205,
        "Status": "Open",
        "image": "/16_6.png",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing12",
        "Course_Duration": 5.3,
        "Level": "Advanced",
        "Enrollment_Count": 1205,
        "Status": "Open",
        "image": "/16_6.png",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing11",
        "Course_Duration": 5.3,
        "Level": "Advanced",
        "Enrollment_Count": 1205,
        "Status": "Open",
        "image": "/16_6.png",
        "userId": 1,
    },
    {
        "Course_Title": "Marketing10",
        "Course_Duration": 6.3,
        "Level": "Advanced",
        "Enrollment_Count": 3405,
        "Status": "Open",
        "image": "/16_6.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development",
        "Course_Duration": 24.3,
        "Level": "Beginner",
        "Enrollment_Count": 58205,
        "Status": "Open",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development1",
        "Course_Duration": 24.3,
        "Level": "Beginner",
        "Enrollment_Count": 58205,
        "Status": "Open",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development2",
        "Course_Duration": 24.3,
        "Level": "Beginner",
        "Enrollment_Count": 58205,
        "Status": "Open",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development3",
        "Course_Duration": 24.3,
        "Level": "Beginner",
        "Enrollment_Count": 58205,
        "Status": "Open",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development4",
        "Course_Duration": 24.3,
        "Level": "Beginner",
        "Enrollment_Count": 58205,
        "Status": "Open",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development5",
        "Course_Duration": 24.3,
        "Level": "Beginner",
        "Enrollment_Count": 58205,
        "Status": "Open",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development6",
        "Course_Duration": 12.5,
        "Level": "Intermediate",
        "Enrollment_Count": 668,
        "Status": "Closed",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development7",
        "Course_Duration": 12.5,
        "Level": "Intermediate",
        "Enrollment_Count": 668,
        "Status": "Closed",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development8",
        "Course_Duration": 12.5,
        "Level": "Intermediate",
        "Enrollment_Count": 668,
        "Status": "Closed",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development9",
        "Course_Duration": 12.5,
        "Level": "Intermediate",
        "Enrollment_Count": 668,
        "Status": "Closed",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Front-End Development10",
        "Course_Duration": 12.5,
        "Level": "Intermediate",
        "Enrollment_Count": 668,
        "Status": "Closed",
        "image": "/16_4.png",
        "userId": 2,
    },
    {
        "Course_Title": "Back-End Development1",
        "Course_Duration": 3,
        "Level": "Beginner",
        "Enrollment_Count": 58,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development2",
        "Course_Duration": 3,
        "Level": "Beginner",
        "Enrollment_Count": 58,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development3",
        "Course_Duration": 3,
        "Level": "Beginner",
        "Enrollment_Count": 58,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development4",
        "Course_Duration": 3,
        "Level": "Beginner",
        "Enrollment_Count": 98,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development5",
        "Course_Duration": 3,
        "Level": "Beginner",
        "Enrollment_Count": 98,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development6",
        "Course_Duration": 3,
        "Level": "Advanced",
        "Enrollment_Count": 98,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development7",
        "Course_Duration": 3,
        "Level": "Advanced",
        "Enrollment_Count": 98,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development8",
        "Course_Duration": 3,
        "Level": "Advanced",
        "Enrollment_Count": 198,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development9",
        "Course_Duration": 3,
        "Level": "Advanced",
        "Enrollment_Count": 198,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Back-End Development10",
        "Course_Duration": 3,
        "Level": "Advanced",
        "Enrollment_Count": 198,
        "Status": "Open",
        "image": "/16_9.png",
        "userId": 3,
    },
    {
        "Course_Title": "Basic HTML and Java1",
        "Course_Duration": 14.4,
        "Level": "Advanced",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java2",
        "Course_Duration": 14.4,
        "Level": "Advanced",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java3",
        "Course_Duration": 14.4,
        "Level": "Advanced",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java4",
        "Course_Duration": 14.4,
        "Level": "Advanced",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java5",
        "Course_Duration": 14.2,
        "Level": "Intermediate",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java6",
        "Course_Duration": 14.2,
        "Level": "Intermediate",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java7",
        "Course_Duration": 14.2,
        "Level": "Intermediate",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java8",
        "Course_Duration": 14.2,
        "Level": "Intermediate",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java9",
        "Course_Duration": 14.2,
        "Level": "Beginner",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Basic HTML and Java10",
        "Course_Duration": 14.2,
        "Level": "Beginner",
        "Enrollment_Count": 1,
        "Status": "Open",
        "image": "/16_i.png",
        "userId": 4,
    },
    {
        "Course_Title": "Data Analytics1",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics2",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics3",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics4",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics5",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics6",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics7",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics8",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics9",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Data Analytics10",
        "Course_Duration": 6.2,
        "Level": "Beginner",
        "Enrollment_Count": 17,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/180/2400/1600.jpg?hmac=Ig-CXcpNdmh51k3kXpNqNqcDYTwXCIaonYiBOnLXBb8",
        "userId": 5,
    },
    {
        "Course_Title": "Full-Stack Software Development1",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development2",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development3",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development4",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development5",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Closed",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development6",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development7",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development8",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development9",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development10",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development11",
        "Course_Duration": 80,
        "Level": "Intermediate",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development12",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development13",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development14",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development15",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development16",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development17",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/119/3264/2176.jpg?hmac=PYRYBOGQhlUm6wS94EkpN8dTIC7-2GniC3pqOt6CpNU",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development18",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/60/1920/1200.jpg?hmac=fAMNjl4E_sG_WNUjdU39Kald5QAHQMh-_-TsIbbeDNI",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development19",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/60/1920/1200.jpg?hmac=fAMNjl4E_sG_WNUjdU39Kald5QAHQMh-_-TsIbbeDNI",
        "userId": 6,
    },
    {
        "Course_Title": "Full-Stack Software Development20",
        "Course_Duration": 80,
        "Level": "Advanced",
        "Enrollment_Count": 33,
        "Status": "Open",
        "image": "https://fastly.picsum.photos/id/60/1920/1200.jpg?hmac=fAMNjl4E_sG_WNUjdU39Kald5QAHQMh-_-TsIbbeDNI",
        "userId": 6,
    }
]
export default courses;